---
- hosts: all
  become: true
  tasks:
    - name: get the docker file
      git: repo=https://github.com/kalyanramudu/demo1.git dest=/home/kalyan/dockerdir
    - name: build the dockerfile
      command: chdir=/home/kalyan/ docker build -t myimage:latest .
    - name: run the dockerimage
      command: docker run -d --name kalyan -P myimage:latest
      
  

    - name: remove container
      docker_container:
        name: kalyan
        state: absent
      when: (result is failed) or (fatal: [172.31.81.42]: FAILED!)
      ignore_errors: true

