---
- hosts: 172.31.81.42
  become: true

  tasks:
    - service: name=docker state=restarted
    - name: Install docker
      apt: name=docker-ce state=present
    - name: start docker
      service: name=docker state=started
